# Generated by Django 3.1.1 on 2020-09-22 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, unique=True)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counties', to='appointment.city')),
            ],
            options={
                'verbose_name': 'County',
                'verbose_name_plural': 'Counties',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitals', to='appointment.county')),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitals',
            },
        ),
        migrations.CreateModel(
            name='Polyclinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polyclinics', to='appointment.hospital')),
            ],
            options={
                'verbose_name': 'Polyclinic',
                'verbose_name_plural': 'Polyclinics',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('identification_number', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('blood_group', models.CharField(blank=True, choices=[('0 Rh-', '0 Rh-'), ('0 Rh+', '0 Rh+'), ('A Rh-', 'A Rh-'), ('A Rh+', 'A Rh+'), ('B Rh-', 'B Rh-'), ('B Rh+', 'B Rh+'), ('AB Rh-', 'AB Rh-'), ('AB Rh+', 'AB Rh+')], max_length=7, null=True)),
                ('mother_name', models.CharField(max_length=15)),
                ('father_name', models.CharField(max_length=15)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('birth_place', models.CharField(blank=True, max_length=15, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Man', 'Erkek'), ('Woman', 'Kadın')], max_length=5, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('identification_number', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('expertise', models.CharField(max_length=25)),
                ('birth_place', models.CharField(blank=True, max_length=15, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Man', 'Erkek'), ('Woman', 'Kadın')], max_length=5, null=True)),
                ('polyclinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='appointment.polyclinic')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointment.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointment.patient')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
            },
        ),
    ]
