# Generated by Django 3.1.1 on 2020-09-22 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birth_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.city'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='father_name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mother_name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
