# Generated by Django 3.1.1 on 2020-09-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20200922_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='identification_number',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='identification_number',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
