# Generated by Django 2.0.13 on 2019-03-19 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randevu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='end_time_of_appointment',
        ),
        migrations.AlterField(
            model_name='patients',
            name='blood_group_of_patient',
            field=models.CharField(max_length=5, verbose_name='Kan Grubu'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='gender_of_patient',
            field=models.CharField(max_length=5, verbose_name='Cinsiyet'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='patient_date_of_birth',
            field=models.DateField(default=datetime.date.today, verbose_name='Doğum Tarihi'),
        ),
    ]
